const chatDetails = [
  {
    "id": 1,
    "isMe": false,
    "profile": " ",
    "message": "",
    "messageNo": 1,
  },
  {
    "id": 2,
    "isMe": false,
    "profile": " ",
    "message": "",
    "messageNo": 3,
  },
  {
    "id": 3,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 1,
  },
  {
    "id": 4,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 2,
  },
  {
    "id": 5,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 3,
  },
  {
    "id": 6,
    "isMe": false,
    "profile": " ",
    "message": "",
    "messageNo": 0,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 1,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 3,
  },
  {
    "id": 7,
    "isMe": false,
    "profile": " ",
    "message": "",
    "messageNo": 1,
  },
  {
    "id": 8,
    "isMe": false,
    "profile": " ",
    "message": "",
    "messageNo": 3,
  },
  {
    "id": 9,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 1,
  },
  {
    "id": 10,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 3,
  },
  {
    "id": 11,
    "isMe": false,
    "profile": " ",
    "message": "",
    "messageNo": 0,
  },
  {
    "id": 12,
    "isMe": true,
    "profile": "",
    "message": "",
    "messageNo": 0,
  },
];